// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CHAT_CHATAPP_H_
#define FLATBUFFERS_GENERATED_CHAT_CHATAPP_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace ChatApp {

struct User;
struct UserBuilder;

struct RoomMessageItem;
struct RoomMessageItemBuilder;

struct RoomItem;
struct RoomItemBuilder;

struct ClientMessageItem;
struct ClientMessageItemBuilder;

struct ServerMessageItem;
struct ServerMessageItemBuilder;

struct RequestMessageItem;
struct RequestMessageItemBuilder;

struct ClientMessagePayload;
struct ClientMessagePayloadBuilder;

struct ServerMessagePayload;
struct ServerMessagePayloadBuilder;

struct PullMissingMessagePayload;
struct PullMissingMessagePayloadBuilder;

struct RequestRoomHistoryPayload;
struct RequestRoomHistoryPayloadBuilder;

struct RequestMessagePayload;
struct RequestMessagePayloadBuilder;

struct MessageAckPayload;
struct MessageAckPayloadBuilder;

struct HelloMessagePayload;
struct HelloMessagePayloadBuilder;

struct StreamMessagePayload;
struct StreamMessagePayloadBuilder;

struct RootMessage;
struct RootMessageBuilder;

enum MsgContentType : int8_t {
  MsgContentType_Unknown = 0,
  MsgContentType_Text = 1,
  MsgContentType_Image = 2,
  MsgContentType_Audio = 3,
  MsgContentType_MIN = MsgContentType_Unknown,
  MsgContentType_MAX = MsgContentType_Audio
};

inline const MsgContentType (&EnumValuesMsgContentType())[4] {
  static const MsgContentType values[] = {
    MsgContentType_Unknown,
    MsgContentType_Text,
    MsgContentType_Image,
    MsgContentType_Audio
  };
  return values;
}

inline const char * const *EnumNamesMsgContentType() {
  static const char * const names[5] = {
    "Unknown",
    "Text",
    "Image",
    "Audio",
    nullptr
  };
  return names;
}

inline const char *EnumNameMsgContentType(MsgContentType e) {
  if (flatbuffers::IsOutRange(e, MsgContentType_Unknown, MsgContentType_Audio)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMsgContentType()[index];
}

enum AnyPayload : uint8_t {
  AnyPayload_NONE = 0,
  AnyPayload_HelloMessagePayload = 1,
  AnyPayload_ClientMessagePayload = 2,
  AnyPayload_ServerMessagePayload = 3,
  AnyPayload_RequestRoomHistoryPayload = 4,
  AnyPayload_RequestMessagePayload = 5,
  AnyPayload_PullMissingMessagePayload = 6,
  AnyPayload_MessageAckPayload = 7,
  AnyPayload_StreamMessagePayload = 8,
  AnyPayload_MIN = AnyPayload_NONE,
  AnyPayload_MAX = AnyPayload_StreamMessagePayload
};

inline const AnyPayload (&EnumValuesAnyPayload())[9] {
  static const AnyPayload values[] = {
    AnyPayload_NONE,
    AnyPayload_HelloMessagePayload,
    AnyPayload_ClientMessagePayload,
    AnyPayload_ServerMessagePayload,
    AnyPayload_RequestRoomHistoryPayload,
    AnyPayload_RequestMessagePayload,
    AnyPayload_PullMissingMessagePayload,
    AnyPayload_MessageAckPayload,
    AnyPayload_StreamMessagePayload
  };
  return values;
}

inline const char * const *EnumNamesAnyPayload() {
  static const char * const names[10] = {
    "NONE",
    "HelloMessagePayload",
    "ClientMessagePayload",
    "ServerMessagePayload",
    "RequestRoomHistoryPayload",
    "RequestMessagePayload",
    "PullMissingMessagePayload",
    "MessageAckPayload",
    "StreamMessagePayload",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnyPayload(AnyPayload e) {
  if (flatbuffers::IsOutRange(e, AnyPayload_NONE, AnyPayload_StreamMessagePayload)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnyPayload()[index];
}

template<typename T> struct AnyPayloadTraits {
  static const AnyPayload enum_value = AnyPayload_NONE;
};

template<> struct AnyPayloadTraits<ChatApp::HelloMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_HelloMessagePayload;
};

template<> struct AnyPayloadTraits<ChatApp::ClientMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_ClientMessagePayload;
};

template<> struct AnyPayloadTraits<ChatApp::ServerMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_ServerMessagePayload;
};

template<> struct AnyPayloadTraits<ChatApp::RequestRoomHistoryPayload> {
  static const AnyPayload enum_value = AnyPayload_RequestRoomHistoryPayload;
};

template<> struct AnyPayloadTraits<ChatApp::RequestMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_RequestMessagePayload;
};

template<> struct AnyPayloadTraits<ChatApp::PullMissingMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_PullMissingMessagePayload;
};

template<> struct AnyPayloadTraits<ChatApp::MessageAckPayload> {
  static const AnyPayload enum_value = AnyPayload_MessageAckPayload;
};

template<> struct AnyPayloadTraits<ChatApp::StreamMessagePayload> {
  static const AnyPayload enum_value = AnyPayload_StreamMessagePayload;
};

bool VerifyAnyPayload(flatbuffers::Verifier &verifier, const void *obj, AnyPayload type);
bool VerifyAnyPayloadVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct User FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UserBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERID = 4,
    VT_USERNAME = 6
  };
  int64_t userid() const {
    return GetField<int64_t>(VT_USERID, 0);
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_USERID, 8) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           verifier.EndTable();
  }
};

struct UserBuilder {
  typedef User Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_userid(int64_t userid) {
    fbb_.AddElement<int64_t>(User::VT_USERID, userid, 0);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(User::VT_USERNAME, username);
  }
  explicit UserBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<User> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<User>(end);
    return o;
  }
};

inline flatbuffers::Offset<User> CreateUser(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t userid = 0,
    flatbuffers::Offset<flatbuffers::String> username = 0) {
  UserBuilder builder_(_fbb);
  builder_.add_userid(userid);
  builder_.add_username(username);
  return builder_.Finish();
}

inline flatbuffers::Offset<User> CreateUserDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t userid = 0,
    const char *username = nullptr) {
  auto username__ = username ? _fbb.CreateString(username) : 0;
  return ChatApp::CreateUser(
      _fbb,
      userid,
      username__);
}

struct RoomMessageItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RoomMessageItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CONTENT = 6,
    VT_USER = 8,
    VT_TIMESTAMP = 10
  };
  const flatbuffers::String *id() const {
    return GetPointer<const flatbuffers::String *>(VT_ID);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  const ChatApp::User *user() const {
    return GetPointer<const ChatApp::User *>(VT_USER);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyOffset(verifier, VT_USER) &&
           verifier.VerifyTable(user()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct RoomMessageItemBuilder {
  typedef RoomMessageItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(flatbuffers::Offset<flatbuffers::String> id) {
    fbb_.AddOffset(RoomMessageItem::VT_ID, id);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(RoomMessageItem::VT_CONTENT, content);
  }
  void add_user(flatbuffers::Offset<ChatApp::User> user) {
    fbb_.AddOffset(RoomMessageItem::VT_USER, user);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(RoomMessageItem::VT_TIMESTAMP, timestamp, 0);
  }
  explicit RoomMessageItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RoomMessageItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RoomMessageItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<RoomMessageItem> CreateRoomMessageItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  RoomMessageItemBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_user(user);
  builder_.add_content(content);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<RoomMessageItem> CreateRoomMessageItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *content = nullptr,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return ChatApp::CreateRoomMessageItem(
      _fbb,
      id__,
      content__,
      user,
      timestamp);
}

struct RoomItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RoomItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HAS_MORE_MESSAGES = 4,
    VT_ROOM_ID = 6,
    VT_ROOMNAME = 8,
    VT_MESSAGES = 10
  };
  bool has_more_messages() const {
    return GetField<uint8_t>(VT_HAS_MORE_MESSAGES, 0) != 0;
  }
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  const flatbuffers::String *roomname() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOMNAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomMessageItem>> *messages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomMessageItem>> *>(VT_MESSAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_HAS_MORE_MESSAGES, 1) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyOffset(verifier, VT_ROOMNAME) &&
           verifier.VerifyString(roomname()) &&
           VerifyOffset(verifier, VT_MESSAGES) &&
           verifier.VerifyVector(messages()) &&
           verifier.VerifyVectorOfTables(messages()) &&
           verifier.EndTable();
  }
};

struct RoomItemBuilder {
  typedef RoomItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_has_more_messages(bool has_more_messages) {
    fbb_.AddElement<uint8_t>(RoomItem::VT_HAS_MORE_MESSAGES, static_cast<uint8_t>(has_more_messages), 0);
  }
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(RoomItem::VT_ROOM_ID, room_id);
  }
  void add_roomname(flatbuffers::Offset<flatbuffers::String> roomname) {
    fbb_.AddOffset(RoomItem::VT_ROOMNAME, roomname);
  }
  void add_messages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomMessageItem>>> messages) {
    fbb_.AddOffset(RoomItem::VT_MESSAGES, messages);
  }
  explicit RoomItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RoomItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RoomItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<RoomItem> CreateRoomItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool has_more_messages = false,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    flatbuffers::Offset<flatbuffers::String> roomname = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomMessageItem>>> messages = 0) {
  RoomItemBuilder builder_(_fbb);
  builder_.add_messages(messages);
  builder_.add_roomname(roomname);
  builder_.add_room_id(room_id);
  builder_.add_has_more_messages(has_more_messages);
  return builder_.Finish();
}

inline flatbuffers::Offset<RoomItem> CreateRoomItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool has_more_messages = false,
    const char *room_id = nullptr,
    const char *roomname = nullptr,
    const std::vector<flatbuffers::Offset<ChatApp::RoomMessageItem>> *messages = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto roomname__ = roomname ? _fbb.CreateString(roomname) : 0;
  auto messages__ = messages ? _fbb.CreateVector<flatbuffers::Offset<ChatApp::RoomMessageItem>>(*messages) : 0;
  return ChatApp::CreateRoomItem(
      _fbb,
      has_more_messages,
      room_id__,
      roomname__,
      messages__);
}

struct ClientMessageItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ClientMessageItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4,
    VT_MSG_TYPE = 6
  };
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  ChatApp::MsgContentType msg_type() const {
    return static_cast<ChatApp::MsgContentType>(GetField<int8_t>(VT_MSG_TYPE, 1));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyField<int8_t>(verifier, VT_MSG_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct ClientMessageItemBuilder {
  typedef ClientMessageItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(ClientMessageItem::VT_CONTENT, content);
  }
  void add_msg_type(ChatApp::MsgContentType msg_type) {
    fbb_.AddElement<int8_t>(ClientMessageItem::VT_MSG_TYPE, static_cast<int8_t>(msg_type), 1);
  }
  explicit ClientMessageItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ClientMessageItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ClientMessageItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<ClientMessageItem> CreateClientMessageItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    ChatApp::MsgContentType msg_type = ChatApp::MsgContentType_Text) {
  ClientMessageItemBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<ClientMessageItem> CreateClientMessageItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *content = nullptr,
    ChatApp::MsgContentType msg_type = ChatApp::MsgContentType_Text) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return ChatApp::CreateClientMessageItem(
      _fbb,
      content__,
      msg_type);
}

struct ServerMessageItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ServerMessageItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_MESSAGE_ID = 4,
    VT_SERVER_MESSAGE_ID = 6,
    VT_CONTENT = 8,
    VT_USER = 10,
    VT_TIMESTAMP = 12
  };
  const flatbuffers::String *client_message_id() const {
    return GetPointer<const flatbuffers::String *>(VT_CLIENT_MESSAGE_ID);
  }
  int64_t server_message_id() const {
    return GetField<int64_t>(VT_SERVER_MESSAGE_ID, 0);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  const ChatApp::User *user() const {
    return GetPointer<const ChatApp::User *>(VT_USER);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CLIENT_MESSAGE_ID) &&
           verifier.VerifyString(client_message_id()) &&
           VerifyField<int64_t>(verifier, VT_SERVER_MESSAGE_ID, 8) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyOffset(verifier, VT_USER) &&
           verifier.VerifyTable(user()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct ServerMessageItemBuilder {
  typedef ServerMessageItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_client_message_id(flatbuffers::Offset<flatbuffers::String> client_message_id) {
    fbb_.AddOffset(ServerMessageItem::VT_CLIENT_MESSAGE_ID, client_message_id);
  }
  void add_server_message_id(int64_t server_message_id) {
    fbb_.AddElement<int64_t>(ServerMessageItem::VT_SERVER_MESSAGE_ID, server_message_id, 0);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(ServerMessageItem::VT_CONTENT, content);
  }
  void add_user(flatbuffers::Offset<ChatApp::User> user) {
    fbb_.AddOffset(ServerMessageItem::VT_USER, user);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(ServerMessageItem::VT_TIMESTAMP, timestamp, 0);
  }
  explicit ServerMessageItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ServerMessageItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ServerMessageItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<ServerMessageItem> CreateServerMessageItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> client_message_id = 0,
    int64_t server_message_id = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  ServerMessageItemBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_server_message_id(server_message_id);
  builder_.add_user(user);
  builder_.add_content(content);
  builder_.add_client_message_id(client_message_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<ServerMessageItem> CreateServerMessageItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *client_message_id = nullptr,
    int64_t server_message_id = 0,
    const char *content = nullptr,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  auto client_message_id__ = client_message_id ? _fbb.CreateString(client_message_id) : 0;
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return ChatApp::CreateServerMessageItem(
      _fbb,
      client_message_id__,
      server_message_id,
      content__,
      user,
      timestamp);
}

struct RequestMessageItem FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RequestMessageItemBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CONTENT = 6,
    VT_USER = 8,
    VT_TIMESTAMP = 10
  };
  const flatbuffers::String *id() const {
    return GetPointer<const flatbuffers::String *>(VT_ID);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  const ChatApp::User *user() const {
    return GetPointer<const ChatApp::User *>(VT_USER);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyOffset(verifier, VT_USER) &&
           verifier.VerifyTable(user()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct RequestMessageItemBuilder {
  typedef RequestMessageItem Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(flatbuffers::Offset<flatbuffers::String> id) {
    fbb_.AddOffset(RequestMessageItem::VT_ID, id);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(RequestMessageItem::VT_CONTENT, content);
  }
  void add_user(flatbuffers::Offset<ChatApp::User> user) {
    fbb_.AddOffset(RequestMessageItem::VT_USER, user);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(RequestMessageItem::VT_TIMESTAMP, timestamp, 0);
  }
  explicit RequestMessageItemBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RequestMessageItem> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RequestMessageItem>(end);
    return o;
  }
};

inline flatbuffers::Offset<RequestMessageItem> CreateRequestMessageItem(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> id = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  RequestMessageItemBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_user(user);
  builder_.add_content(content);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<RequestMessageItem> CreateRequestMessageItemDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *content = nullptr,
    flatbuffers::Offset<ChatApp::User> user = 0,
    int64_t timestamp = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return ChatApp::CreateRequestMessageItem(
      _fbb,
      id__,
      content__,
      user,
      timestamp);
}

struct ClientMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ClientMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4,
    VT_CLIENT_MESSAGE_ID = 6,
    VT_MESSAGES = 8
  };
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  const flatbuffers::String *client_message_id() const {
    return GetPointer<const flatbuffers::String *>(VT_CLIENT_MESSAGE_ID);
  }
  const flatbuffers::Vector<flatbuffers::Offset<ChatApp::ClientMessageItem>> *messages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ChatApp::ClientMessageItem>> *>(VT_MESSAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyOffset(verifier, VT_CLIENT_MESSAGE_ID) &&
           verifier.VerifyString(client_message_id()) &&
           VerifyOffset(verifier, VT_MESSAGES) &&
           verifier.VerifyVector(messages()) &&
           verifier.VerifyVectorOfTables(messages()) &&
           verifier.EndTable();
  }
};

struct ClientMessagePayloadBuilder {
  typedef ClientMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(ClientMessagePayload::VT_ROOM_ID, room_id);
  }
  void add_client_message_id(flatbuffers::Offset<flatbuffers::String> client_message_id) {
    fbb_.AddOffset(ClientMessagePayload::VT_CLIENT_MESSAGE_ID, client_message_id);
  }
  void add_messages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::ClientMessageItem>>> messages) {
    fbb_.AddOffset(ClientMessagePayload::VT_MESSAGES, messages);
  }
  explicit ClientMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ClientMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ClientMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<ClientMessagePayload> CreateClientMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    flatbuffers::Offset<flatbuffers::String> client_message_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::ClientMessageItem>>> messages = 0) {
  ClientMessagePayloadBuilder builder_(_fbb);
  builder_.add_messages(messages);
  builder_.add_client_message_id(client_message_id);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<ClientMessagePayload> CreateClientMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *room_id = nullptr,
    const char *client_message_id = nullptr,
    const std::vector<flatbuffers::Offset<ChatApp::ClientMessageItem>> *messages = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto client_message_id__ = client_message_id ? _fbb.CreateString(client_message_id) : 0;
  auto messages__ = messages ? _fbb.CreateVector<flatbuffers::Offset<ChatApp::ClientMessageItem>>(*messages) : 0;
  return ChatApp::CreateClientMessagePayload(
      _fbb,
      room_id__,
      client_message_id__,
      messages__);
}

struct ServerMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ServerMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4,
    VT_MESSAGES = 6
  };
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  const flatbuffers::Vector<flatbuffers::Offset<ChatApp::ServerMessageItem>> *messages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ChatApp::ServerMessageItem>> *>(VT_MESSAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyOffset(verifier, VT_MESSAGES) &&
           verifier.VerifyVector(messages()) &&
           verifier.VerifyVectorOfTables(messages()) &&
           verifier.EndTable();
  }
};

struct ServerMessagePayloadBuilder {
  typedef ServerMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(ServerMessagePayload::VT_ROOM_ID, room_id);
  }
  void add_messages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::ServerMessageItem>>> messages) {
    fbb_.AddOffset(ServerMessagePayload::VT_MESSAGES, messages);
  }
  explicit ServerMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ServerMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ServerMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<ServerMessagePayload> CreateServerMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::ServerMessageItem>>> messages = 0) {
  ServerMessagePayloadBuilder builder_(_fbb);
  builder_.add_messages(messages);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<ServerMessagePayload> CreateServerMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *room_id = nullptr,
    const std::vector<flatbuffers::Offset<ChatApp::ServerMessageItem>> *messages = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto messages__ = messages ? _fbb.CreateVector<flatbuffers::Offset<ChatApp::ServerMessageItem>>(*messages) : 0;
  return ChatApp::CreateServerMessagePayload(
      _fbb,
      room_id__,
      messages__);
}

struct PullMissingMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PullMissingMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4,
    VT_MISSING_MESSAGE_IDS = 6
  };
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  const flatbuffers::Vector<int64_t> *missing_message_ids() const {
    return GetPointer<const flatbuffers::Vector<int64_t> *>(VT_MISSING_MESSAGE_IDS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyOffset(verifier, VT_MISSING_MESSAGE_IDS) &&
           verifier.VerifyVector(missing_message_ids()) &&
           verifier.EndTable();
  }
};

struct PullMissingMessagePayloadBuilder {
  typedef PullMissingMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(PullMissingMessagePayload::VT_ROOM_ID, room_id);
  }
  void add_missing_message_ids(flatbuffers::Offset<flatbuffers::Vector<int64_t>> missing_message_ids) {
    fbb_.AddOffset(PullMissingMessagePayload::VT_MISSING_MESSAGE_IDS, missing_message_ids);
  }
  explicit PullMissingMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PullMissingMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PullMissingMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<PullMissingMessagePayload> CreatePullMissingMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<int64_t>> missing_message_ids = 0) {
  PullMissingMessagePayloadBuilder builder_(_fbb);
  builder_.add_missing_message_ids(missing_message_ids);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<PullMissingMessagePayload> CreatePullMissingMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *room_id = nullptr,
    const std::vector<int64_t> *missing_message_ids = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto missing_message_ids__ = missing_message_ids ? _fbb.CreateVector<int64_t>(*missing_message_ids) : 0;
  return ChatApp::CreatePullMissingMessagePayload(
      _fbb,
      room_id__,
      missing_message_ids__);
}

struct RequestRoomHistoryPayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RequestRoomHistoryPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4,
    VT_COUNT = 6,
    VT_FIRST_MESSAGE_ID = 8
  };
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  int64_t count() const {
    return GetField<int64_t>(VT_COUNT, 0);
  }
  const flatbuffers::String *first_message_id() const {
    return GetPointer<const flatbuffers::String *>(VT_FIRST_MESSAGE_ID);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyField<int64_t>(verifier, VT_COUNT, 8) &&
           VerifyOffset(verifier, VT_FIRST_MESSAGE_ID) &&
           verifier.VerifyString(first_message_id()) &&
           verifier.EndTable();
  }
};

struct RequestRoomHistoryPayloadBuilder {
  typedef RequestRoomHistoryPayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(RequestRoomHistoryPayload::VT_ROOM_ID, room_id);
  }
  void add_count(int64_t count) {
    fbb_.AddElement<int64_t>(RequestRoomHistoryPayload::VT_COUNT, count, 0);
  }
  void add_first_message_id(flatbuffers::Offset<flatbuffers::String> first_message_id) {
    fbb_.AddOffset(RequestRoomHistoryPayload::VT_FIRST_MESSAGE_ID, first_message_id);
  }
  explicit RequestRoomHistoryPayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RequestRoomHistoryPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RequestRoomHistoryPayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<RequestRoomHistoryPayload> CreateRequestRoomHistoryPayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    int64_t count = 0,
    flatbuffers::Offset<flatbuffers::String> first_message_id = 0) {
  RequestRoomHistoryPayloadBuilder builder_(_fbb);
  builder_.add_count(count);
  builder_.add_first_message_id(first_message_id);
  builder_.add_room_id(room_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<RequestRoomHistoryPayload> CreateRequestRoomHistoryPayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *room_id = nullptr,
    int64_t count = 0,
    const char *first_message_id = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto first_message_id__ = first_message_id ? _fbb.CreateString(first_message_id) : 0;
  return ChatApp::CreateRequestRoomHistoryPayload(
      _fbb,
      room_id__,
      count,
      first_message_id__);
}

struct RequestMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RequestMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_ID = 4,
    VT_ROOMNAME = 6,
    VT_HAS_MORE_MESSAGES = 8,
    VT_MESSAGES = 10
  };
  const flatbuffers::String *room_id() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOM_ID);
  }
  const flatbuffers::String *roomname() const {
    return GetPointer<const flatbuffers::String *>(VT_ROOMNAME);
  }
  bool has_more_messages() const {
    return GetField<uint8_t>(VT_HAS_MORE_MESSAGES, 0) != 0;
  }
  const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RequestMessageItem>> *messages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RequestMessageItem>> *>(VT_MESSAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ROOM_ID) &&
           verifier.VerifyString(room_id()) &&
           VerifyOffset(verifier, VT_ROOMNAME) &&
           verifier.VerifyString(roomname()) &&
           VerifyField<uint8_t>(verifier, VT_HAS_MORE_MESSAGES, 1) &&
           VerifyOffset(verifier, VT_MESSAGES) &&
           verifier.VerifyVector(messages()) &&
           verifier.VerifyVectorOfTables(messages()) &&
           verifier.EndTable();
  }
};

struct RequestMessagePayloadBuilder {
  typedef RequestMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_id(flatbuffers::Offset<flatbuffers::String> room_id) {
    fbb_.AddOffset(RequestMessagePayload::VT_ROOM_ID, room_id);
  }
  void add_roomname(flatbuffers::Offset<flatbuffers::String> roomname) {
    fbb_.AddOffset(RequestMessagePayload::VT_ROOMNAME, roomname);
  }
  void add_has_more_messages(bool has_more_messages) {
    fbb_.AddElement<uint8_t>(RequestMessagePayload::VT_HAS_MORE_MESSAGES, static_cast<uint8_t>(has_more_messages), 0);
  }
  void add_messages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RequestMessageItem>>> messages) {
    fbb_.AddOffset(RequestMessagePayload::VT_MESSAGES, messages);
  }
  explicit RequestMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RequestMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RequestMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<RequestMessagePayload> CreateRequestMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> room_id = 0,
    flatbuffers::Offset<flatbuffers::String> roomname = 0,
    bool has_more_messages = false,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RequestMessageItem>>> messages = 0) {
  RequestMessagePayloadBuilder builder_(_fbb);
  builder_.add_messages(messages);
  builder_.add_roomname(roomname);
  builder_.add_room_id(room_id);
  builder_.add_has_more_messages(has_more_messages);
  return builder_.Finish();
}

inline flatbuffers::Offset<RequestMessagePayload> CreateRequestMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *room_id = nullptr,
    const char *roomname = nullptr,
    bool has_more_messages = false,
    const std::vector<flatbuffers::Offset<ChatApp::RequestMessageItem>> *messages = nullptr) {
  auto room_id__ = room_id ? _fbb.CreateString(room_id) : 0;
  auto roomname__ = roomname ? _fbb.CreateString(roomname) : 0;
  auto messages__ = messages ? _fbb.CreateVector<flatbuffers::Offset<ChatApp::RequestMessageItem>>(*messages) : 0;
  return ChatApp::CreateRequestMessagePayload(
      _fbb,
      room_id__,
      roomname__,
      has_more_messages,
      messages__);
}

struct MessageAckPayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageAckPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_MESSAGE_ID = 4,
    VT_STATUS = 6
  };
  const flatbuffers::String *client_message_id() const {
    return GetPointer<const flatbuffers::String *>(VT_CLIENT_MESSAGE_ID);
  }
  const flatbuffers::String *status() const {
    return GetPointer<const flatbuffers::String *>(VT_STATUS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CLIENT_MESSAGE_ID) &&
           verifier.VerifyString(client_message_id()) &&
           VerifyOffset(verifier, VT_STATUS) &&
           verifier.VerifyString(status()) &&
           verifier.EndTable();
  }
};

struct MessageAckPayloadBuilder {
  typedef MessageAckPayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_client_message_id(flatbuffers::Offset<flatbuffers::String> client_message_id) {
    fbb_.AddOffset(MessageAckPayload::VT_CLIENT_MESSAGE_ID, client_message_id);
  }
  void add_status(flatbuffers::Offset<flatbuffers::String> status) {
    fbb_.AddOffset(MessageAckPayload::VT_STATUS, status);
  }
  explicit MessageAckPayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MessageAckPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MessageAckPayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<MessageAckPayload> CreateMessageAckPayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> client_message_id = 0,
    flatbuffers::Offset<flatbuffers::String> status = 0) {
  MessageAckPayloadBuilder builder_(_fbb);
  builder_.add_status(status);
  builder_.add_client_message_id(client_message_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<MessageAckPayload> CreateMessageAckPayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *client_message_id = nullptr,
    const char *status = nullptr) {
  auto client_message_id__ = client_message_id ? _fbb.CreateString(client_message_id) : 0;
  auto status__ = status ? _fbb.CreateString(status) : 0;
  return ChatApp::CreateMessageAckPayload(
      _fbb,
      client_message_id__,
      status__);
}

struct HelloMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef HelloMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ME = 4,
    VT_ROOMS = 6
  };
  const ChatApp::User *me() const {
    return GetPointer<const ChatApp::User *>(VT_ME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomItem>> *rooms() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomItem>> *>(VT_ROOMS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ME) &&
           verifier.VerifyTable(me()) &&
           VerifyOffset(verifier, VT_ROOMS) &&
           verifier.VerifyVector(rooms()) &&
           verifier.VerifyVectorOfTables(rooms()) &&
           verifier.EndTable();
  }
};

struct HelloMessagePayloadBuilder {
  typedef HelloMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_me(flatbuffers::Offset<ChatApp::User> me) {
    fbb_.AddOffset(HelloMessagePayload::VT_ME, me);
  }
  void add_rooms(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomItem>>> rooms) {
    fbb_.AddOffset(HelloMessagePayload::VT_ROOMS, rooms);
  }
  explicit HelloMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<HelloMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<HelloMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<HelloMessagePayload> CreateHelloMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<ChatApp::User> me = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<ChatApp::RoomItem>>> rooms = 0) {
  HelloMessagePayloadBuilder builder_(_fbb);
  builder_.add_rooms(rooms);
  builder_.add_me(me);
  return builder_.Finish();
}

inline flatbuffers::Offset<HelloMessagePayload> CreateHelloMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<ChatApp::User> me = 0,
    const std::vector<flatbuffers::Offset<ChatApp::RoomItem>> *rooms = nullptr) {
  auto rooms__ = rooms ? _fbb.CreateVector<flatbuffers::Offset<ChatApp::RoomItem>>(*rooms) : 0;
  return ChatApp::CreateHelloMessagePayload(
      _fbb,
      me,
      rooms__);
}

struct StreamMessagePayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef StreamMessagePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT = 4,
    VT_USERID = 6,
    VT_USERNAME = 8,
    VT_TIMESTAMP = 10
  };
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  int64_t userid() const {
    return GetField<int64_t>(VT_USERID, 0);
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyField<int64_t>(verifier, VT_USERID, 8) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct StreamMessagePayloadBuilder {
  typedef StreamMessagePayload Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(StreamMessagePayload::VT_CONTENT, content);
  }
  void add_userid(int64_t userid) {
    fbb_.AddElement<int64_t>(StreamMessagePayload::VT_USERID, userid, 0);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(StreamMessagePayload::VT_USERNAME, username);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(StreamMessagePayload::VT_TIMESTAMP, timestamp, 0);
  }
  explicit StreamMessagePayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<StreamMessagePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<StreamMessagePayload>(end);
    return o;
  }
};

inline flatbuffers::Offset<StreamMessagePayload> CreateStreamMessagePayload(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    int64_t userid = 0,
    flatbuffers::Offset<flatbuffers::String> username = 0,
    int64_t timestamp = 0) {
  StreamMessagePayloadBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_userid(userid);
  builder_.add_username(username);
  builder_.add_content(content);
  return builder_.Finish();
}

inline flatbuffers::Offset<StreamMessagePayload> CreateStreamMessagePayloadDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *content = nullptr,
    int64_t userid = 0,
    const char *username = nullptr,
    int64_t timestamp = 0) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  auto username__ = username ? _fbb.CreateString(username) : 0;
  return ChatApp::CreateStreamMessagePayload(
      _fbb,
      content__,
      userid,
      username__,
      timestamp);
}

struct RootMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RootMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  ChatApp::AnyPayload payload_type() const {
    return static_cast<ChatApp::AnyPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const ChatApp::HelloMessagePayload *payload_as_HelloMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_HelloMessagePayload ? static_cast<const ChatApp::HelloMessagePayload *>(payload()) : nullptr;
  }
  const ChatApp::ClientMessagePayload *payload_as_ClientMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_ClientMessagePayload ? static_cast<const ChatApp::ClientMessagePayload *>(payload()) : nullptr;
  }
  const ChatApp::ServerMessagePayload *payload_as_ServerMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_ServerMessagePayload ? static_cast<const ChatApp::ServerMessagePayload *>(payload()) : nullptr;
  }
  const ChatApp::RequestRoomHistoryPayload *payload_as_RequestRoomHistoryPayload() const {
    return payload_type() == ChatApp::AnyPayload_RequestRoomHistoryPayload ? static_cast<const ChatApp::RequestRoomHistoryPayload *>(payload()) : nullptr;
  }
  const ChatApp::RequestMessagePayload *payload_as_RequestMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_RequestMessagePayload ? static_cast<const ChatApp::RequestMessagePayload *>(payload()) : nullptr;
  }
  const ChatApp::PullMissingMessagePayload *payload_as_PullMissingMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_PullMissingMessagePayload ? static_cast<const ChatApp::PullMissingMessagePayload *>(payload()) : nullptr;
  }
  const ChatApp::MessageAckPayload *payload_as_MessageAckPayload() const {
    return payload_type() == ChatApp::AnyPayload_MessageAckPayload ? static_cast<const ChatApp::MessageAckPayload *>(payload()) : nullptr;
  }
  const ChatApp::StreamMessagePayload *payload_as_StreamMessagePayload() const {
    return payload_type() == ChatApp::AnyPayload_StreamMessagePayload ? static_cast<const ChatApp::StreamMessagePayload *>(payload()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyAnyPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const ChatApp::HelloMessagePayload *RootMessage::payload_as<ChatApp::HelloMessagePayload>() const {
  return payload_as_HelloMessagePayload();
}

template<> inline const ChatApp::ClientMessagePayload *RootMessage::payload_as<ChatApp::ClientMessagePayload>() const {
  return payload_as_ClientMessagePayload();
}

template<> inline const ChatApp::ServerMessagePayload *RootMessage::payload_as<ChatApp::ServerMessagePayload>() const {
  return payload_as_ServerMessagePayload();
}

template<> inline const ChatApp::RequestRoomHistoryPayload *RootMessage::payload_as<ChatApp::RequestRoomHistoryPayload>() const {
  return payload_as_RequestRoomHistoryPayload();
}

template<> inline const ChatApp::RequestMessagePayload *RootMessage::payload_as<ChatApp::RequestMessagePayload>() const {
  return payload_as_RequestMessagePayload();
}

template<> inline const ChatApp::PullMissingMessagePayload *RootMessage::payload_as<ChatApp::PullMissingMessagePayload>() const {
  return payload_as_PullMissingMessagePayload();
}

template<> inline const ChatApp::MessageAckPayload *RootMessage::payload_as<ChatApp::MessageAckPayload>() const {
  return payload_as_MessageAckPayload();
}

template<> inline const ChatApp::StreamMessagePayload *RootMessage::payload_as<ChatApp::StreamMessagePayload>() const {
  return payload_as_StreamMessagePayload();
}

struct RootMessageBuilder {
  typedef RootMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_payload_type(ChatApp::AnyPayload payload_type) {
    fbb_.AddElement<uint8_t>(RootMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RootMessage::VT_PAYLOAD, payload);
  }
  explicit RootMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RootMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RootMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<RootMessage> CreateRootMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    ChatApp::AnyPayload payload_type = ChatApp::AnyPayload_NONE,
    flatbuffers::Offset<void> payload = 0) {
  RootMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyAnyPayload(flatbuffers::Verifier &verifier, const void *obj, AnyPayload type) {
  switch (type) {
    case AnyPayload_NONE: {
      return true;
    }
    case AnyPayload_HelloMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::HelloMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_ClientMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::ClientMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_ServerMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::ServerMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_RequestRoomHistoryPayload: {
      auto ptr = reinterpret_cast<const ChatApp::RequestRoomHistoryPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_RequestMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::RequestMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_PullMissingMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::PullMissingMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_MessageAckPayload: {
      auto ptr = reinterpret_cast<const ChatApp::MessageAckPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyPayload_StreamMessagePayload: {
      auto ptr = reinterpret_cast<const ChatApp::StreamMessagePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyAnyPayloadVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAnyPayload(
        verifier,  values->Get(i), types->GetEnum<AnyPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const ChatApp::RootMessage *GetRootMessage(const void *buf) {
  return flatbuffers::GetRoot<ChatApp::RootMessage>(buf);
}

inline const ChatApp::RootMessage *GetSizePrefixedRootMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ChatApp::RootMessage>(buf);
}

inline bool VerifyRootMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ChatApp::RootMessage>(nullptr);
}

inline bool VerifySizePrefixedRootMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ChatApp::RootMessage>(nullptr);
}

inline void FinishRootMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ChatApp::RootMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ChatApp::RootMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ChatApp

#endif  // FLATBUFFERS_GENERATED_CHAT_CHATAPP_H_
